name: Build packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TSTAG: v1.2.9
    steps:
    - name: Set Tailscale version from source
      run: echo "TSTAG=$(curl https://api.github.com/repos/tailscale/tailscale/tags -s | jq '.[0].name' -r)" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Tailscale build container
      run: make build-tailscaled-container

    - name: Create QDK build container
      run: make build-qdk-container

    - name: Create Tailscale QPKG
      run : make out/pkg

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Tailscale-${{ env.TSTAG }}-QPKG-all
        path: out/pkg/
